
# 第八章：错误处理


## 8.2 抛出和捕获

#### 本小节主要讲了概念```do catch``` ```throws``` 相关的东西

先想想我们在上一节讲了Result类型
##### 知识点1： swift不会返回一个```Result```来表示失败，而是用throws
Result作用于```类型```， throws作用于```函数```

##### 知识点2：编译器会认为throws是一个```普通的返回```，不会像很多语言一样带来运行时的开销。相对```效率高一些```。

我们通过 do catch 去处理一个函数的throws    可以使用catch的匹配模式去捕获具体的错误 或者在catch-all中去捕获其他异常 如下
    
    do{
        
    }catch FileError.fileNotExist {
        //FileError.fileNotExist是自定义的一个错误类型  
    }catch{
        //其他error
    }


#### 自己自定义一个指定的error的用法。
我们可以通过创建自定义Error枚举去捕获对于的错误类型
    
    ///创建error的枚举
    enum MyCustomErrorType: Error {
    case ErrorReasonNoFile
    case ErrorReasonReadWrong
    case ErrorReasonShotDown
    }

    ///假设myThrowFunc函数需要做抛错处理
    func myThrowFunc() throws {
        if 触发了没有文件的错误情况 {
            throw MyCustomErrorType.ErrorReasonNoFile
        }
    }
    
    ///接收对应的error
    do{
        myThrowFunc()
    }catch MyCustomErrorType.ErrorReasonNoFile {
        // 无文件的错误情况
    }catch{
        //其他error
    }

##### 注：无论你有多少个自定义的catch分支  最后都要用一个```catch { }去结尾```，我们认为你无法将所有的error都考虑到。

